modLoader="javafml"
loaderVersion="[36,)"
license="GNU LGPL 3.0"
logoFile="logo.png"
[[mods]]
modId="missingmagic"
version="${file.jarVersion}"
displayName="MissingMagic"
authors="stanuwu"
description='''
Addon for Psi
'''
[[dependencies.missingmagic]]
   modId="forge"
   mandatory=true
   versionRange="[36,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.missingmagic]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.16.5,1.17)"
   ordering="NONE"
   side="BOTH"
[[dependencies.missingmagic]]
    modId="psi"
    mandatory=true
    versionRange="[1.16-95,)"
    ordering="AFTER"
    side="BOTH"
